package itcr.barbero;

public class BarberoMenu extends javax.swing.JFrame {

    private Barbero barbero;

    public BarberoMenu() {

        initComponents();
        deshabilitarBotonCita(); // empezamos deshabilitando el boton cita, hasta que se crea el horario
        // para asi poder evistar confusiones/problemas 
        barbero = new Barbero();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botonHorarioAtencion = new javax.swing.JButton();
        botonClientes = new javax.swing.JButton();
        botonServicios = new javax.swing.JButton();
        botonCitas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvendid@s a la Barberia Orientada a Objetos!");

        jLabel2.setText("En que desea ingresar?");

        botonHorarioAtencion.setText("Horario de Atencion");
        botonHorarioAtencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHorarioAtencionActionPerformed(evt);
            }
        });

        botonClientes.setText("Clientes");
        botonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClientesActionPerformed(evt);
            }
        });

        botonServicios.setText("Servicios");
        botonServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonServiciosActionPerformed(evt);
            }
        });

        botonCitas.setText("Citas");
        botonCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCitasActionPerformed(evt);
            }
        });

        jLabel3.setText("(Le recomendamos iniciando con el horario de atencion)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(180, 180, 180))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonHorarioAtencion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(174, 174, 174))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addComponent(botonHorarioAtencion)
                .addGap(18, 18, 18)
                .addComponent(botonClientes)
                .addGap(18, 18, 18)
                .addComponent(botonServicios)
                .addGap(18, 18, 18)
                .addComponent(botonCitas)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void botonServiciosActionPerformed(java.awt.event.ActionEvent evt) {                                               
        //Boton de servicios
        //String nombre = "";
        //Servicio S = new Servicio(String nombre);
        ServiciosMenu sm = new ServiciosMenu(this); 
        sm.setLocationRelativeTo(this); 
        sm.setVisible(true);


    }                                              

    private void botonHorarioAtencionActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        //Boton de horario de atencion, tengo que ver como cambiarle el nombre sin que pase algo
        HorarioAtencion HA = new HorarioAtencion();
        this.setVisible(false); // al abrir horario de atencion, se cierra el principal
        HorarioAtencionMenu ham = new HorarioAtencionMenu(this, HA); //se crea la instancia de horario de atencion
        ham.setLocationRelativeTo(this); // no se muy bien que hace esto pero sirve igual con o sin pero el profe lo tenia
        ham.setVisible(true); //mostramos la pantalla de horario de atencion


    }                                                    

    public void deshabilitarBotonCita() {
        botonCitas.setEnabled(false);
    }

    public void habilitarBotonCita() {
        botonCitas.setEnabled(true);
    }


    private void botonClientesActionPerformed(java.awt.event.ActionEvent evt) {                                              
        //Boton de Clientes
        this.setVisible(false);
        ClientesMenu clm = new ClientesMenu(this);
        clm.setLocationRelativeTo(this);
        clm.setVisible(true);
    }                                             

    private void botonCitasActionPerformed(java.awt.event.ActionEvent evt) {                                           
        //Boton de citas
        this.setVisible(false);
        CitasMenu cim = new CitasMenu(this);
        cim.setLocationRelativeTo(this);
        cim.setVisible(true); //
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarberoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarberoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarberoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarberoMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarberoMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton botonCitas;
    private javax.swing.JButton botonClientes;
    private javax.swing.JButton botonHorarioAtencion;
    private javax.swing.JButton botonServicios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration                   
}
