
package itcr.barbero;

import java.time.DayOfWeek;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JCheckBox;

public class HorarioAtencionMenu extends javax.swing.JFrame {
    
    private ArrayList<JCheckBox> listaCheckBox;
    private BarberoMenu barberoMenu;
    private HorarioAtencion horario;
    private Barbero barbero;
            
    public HorarioAtencionMenu(BarberoMenu barberoMenu, HorarioAtencion horario) {
        //aqui podemos declarar lo que queremos deshabilitar hasta que pase x situacion
        initComponents();
        this.barberoMenu = barberoMenu;
        this.horario = horario;
        botonContinuar.setEnabled(false);
        ComboBoxLunesApertura.setEnabled(false);
        ComboBoxLunesCierre.setEnabled(false);
        ComboBoxMartesApertura.setEnabled(false);
        ComboBoxMartesCierre.setEnabled(false);
        ComboBoxMiercolesApertura.setEnabled(false);
        ComboBoxMiercolesCierre.setEnabled(false);
        ComboBoxJuevesApertura.setEnabled(false);
        ComboBoxJuevesCierre.setEnabled(false);
        ComboBoxViernesApertura.setEnabled(false);
        ComboBoxViernesCierre.setEnabled(false);
        ComboBoxSabadoApertura.setEnabled(false);
        ComboBoxSabadoCierre.setEnabled(false);
        ComboBoxDomingoApertura.setEnabled(false);
        ComboBoxDomingoCierre.setEnabled(false);
        
        listaCheckBox = new ArrayList<>();
        listaCheckBox.add(CheckBoxLunes);
        listaCheckBox.add(CheckBoxMartes);
        listaCheckBox.add(CheckBoxMiercoles);
        listaCheckBox.add(CheckBoxJueves);
        listaCheckBox.add(jCheckBox6);
        listaCheckBox.add(CheckBoxViernes);
        listaCheckBox.add(CheckBoxSabado);
        listaCheckBox.add(CheckBoxDomingo);
        
        habilitarContinuar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jComboBox15 = new javax.swing.JComboBox<>();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        botonVolver = new javax.swing.JButton();
        botonContinuar = new javax.swing.JButton();
        ComboBoxLunesApertura = new javax.swing.JComboBox<>();
        ComboBoxLunesCierre = new javax.swing.JComboBox<>();
        ComboBoxMartesApertura = new javax.swing.JComboBox<>();
        ComboBoxMartesCierre = new javax.swing.JComboBox<>();
        ComboBoxMiercolesApertura = new javax.swing.JComboBox<>();
        ComboBoxMiercolesCierre = new javax.swing.JComboBox<>();
        ComboBoxJuevesApertura = new javax.swing.JComboBox<>();
        ComboBoxJuevesCierre = new javax.swing.JComboBox<>();
        ComboBoxViernesApertura = new javax.swing.JComboBox<>();
        ComboBoxViernesCierre = new javax.swing.JComboBox<>();
        ComboBoxSabadoApertura = new javax.swing.JComboBox<>();
        ComboBoxSabadoCierre = new javax.swing.JComboBox<>();
        ComboBoxDomingoApertura = new javax.swing.JComboBox<>();
        ComboBoxDomingoCierre = new javax.swing.JComboBox<>();
        CheckBoxLunes = new javax.swing.JCheckBox();
        CheckBoxMartes = new javax.swing.JCheckBox();
        CheckBoxMiercoles = new javax.swing.JCheckBox();
        CheckBoxJueves = new javax.swing.JCheckBox();
        CheckBoxViernes = new javax.swing.JCheckBox();
        CheckBoxSabado = new javax.swing.JCheckBox();
        CheckBoxDomingo = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "000", "100", "200", "300", "400", "500", "600", "700", "800", "900", "1000", "1100", "1200", "1300", "1400", "1500", "1600", "1700", "1800", "1900", "2000", "2100", "2200", "2300", "2400" }));
        jComboBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox15ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Por favor escoja su horario de atencion para los dias de la semana");

        jLabel2.setText("Lunes");

        jLabel3.setText("Martes");

        jLabel4.setText("Miercoles");

        jLabel5.setText("Jueves");

        jLabel6.setText("Viernes");

        jLabel7.setText("Sabado");

        jLabel8.setText("Domingo");

        jLabel9.setText("Hora de Apertura");

        jLabel10.setText("Hora de Cierre");

        jLabel11.setText("Dias");

        botonVolver.setText(" Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        botonContinuar.setText("Continuar");
        botonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContinuarActionPerformed(evt);
            }
        });

        ComboBoxLunesApertura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "000", "100", "200", "300", "400", "500", "600", "700", "800", "900", "1000", "1100", "1200", "1300", "1400", "1500", "1600", "1700", "1800", "1900", "2000", "2100", "2200", "2300", "2400" }));
        ComboBoxLunesApertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxLunesAperturaActionPerformed(evt);
            }
        });

        ComboBoxLunesCierre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "000", "100", "200", "300", "400", "500", "600", "700", "800", "900", "1000", "1100", "1200", "1300", "1400", "1500", "1600", "1700", "1800", "1900", "2000", "2100", "2200", "2300", "2400" }));
        ComboBoxLunesCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxLunesCierreActionPerformed(evt);
            }
        });

        ComboBoxMartesApertura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "000", "100", "200", "300", "400", "500", "600", "700", "800", "900", "1000", "1100", "1200", "1300", "1400", "1500", "1600", "1700", "1800", "1900", "2000", "2100", "2200", "2300", "2400" }));
        ComboBoxMartesApertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMartesAperturaActionPerformed(evt);
            }
        });

        ComboBoxMartesCierre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "000", "100", "200", "300", "400", "500", "600", "700", "800", "900", "1000", "1100", "1200", "1300", "1400", "1500", "1600", "1700", "1800", "1900", "2000", "2100", "2200", "2300", "2400" }));
        ComboBoxMartesCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMartesCierreActionPerformed(evt);
            }
        });

        ComboBoxMiercolesApertura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "000", "100", "200", "300", "400", "500", "600", "700", "800", "900", "1000", "1100", "1200", "1300", "1400", "1500", "1600", "1700", "1800", "1900", "2000", "2100", "2200", "2300", "2400" }));
        ComboBoxMiercolesApertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMiercolesAperturaActionPerformed(evt);
            }
        });

        ComboBoxMiercolesCierre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "000", "100", "200", "300", "400", "500", "600", "700", "800", "900", "1000", "1100", "1200", "1300", "1400", "1500", "1600", "1700", "1800", "1900", "2000", "2100", "2200", "2300", "2400" }));
        ComboBoxMiercolesCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMiercolesCierreActionPerformed(evt);
            }
        });

        ComboBoxJuevesApertura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "000", "100", "200", "300", "400", "500", "600", "700", "800", "900", "1000", "1100", "1200", "1300", "1400", "1500", "1600", "1700", "1800", "1900", "2000", "2100", "2200", "2300", "2400" }));
        ComboBoxJuevesApertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxJuevesAperturaActionPerformed(evt);
            }
        });

        ComboBoxJuevesCierre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "000", "100", "200", "300", "400", "500", "600", "700", "800", "900", "1000", "1100", "1200", "1300", "1400", "1500", "1600", "1700", "1800", "1900", "2000", "2100", "2200", "2300", "2400" }));
        ComboBoxJuevesCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxJuevesCierreActionPerformed(evt);
            }
        });

        ComboBoxViernesApertura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "000", "100", "200", "300", "400", "500", "600", "700", "800", "900", "1000", "1100", "1200", "1300", "1400", "1500", "1600", "1700", "1800", "1900", "2000", "2100", "2200", "2300", "2400" }));
        ComboBoxViernesApertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxViernesAperturaActionPerformed(evt);
            }
        });

        ComboBoxViernesCierre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "000", "100", "200", "300", "400", "500", "600", "700", "800", "900", "1000", "1100", "1200", "1300", "1400", "1500", "1600", "1700", "1800", "1900", "2000", "2100", "2200", "2300", "2400" }));
        ComboBoxViernesCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxViernesCierreActionPerformed(evt);
            }
        });

        ComboBoxSabadoApertura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "000", "100", "200", "300", "400", "500", "600", "700", "800", "900", "1000", "1100", "1200", "1300", "1400", "1500", "1600", "1700", "1800", "1900", "2000", "2100", "2200", "2300", "2400" }));
        ComboBoxSabadoApertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxSabadoAperturaActionPerformed(evt);
            }
        });

        ComboBoxSabadoCierre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "000", "100", "200", "300", "400", "500", "600", "700", "800", "900", "1000", "1100", "1200", "1300", "1400", "1500", "1600", "1700", "1800", "1900", "2000", "2100", "2200", "2300", "2400" }));
        ComboBoxSabadoCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxSabadoCierreActionPerformed(evt);
            }
        });

        ComboBoxDomingoApertura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "000", "100", "200", "300", "400", "500", "600", "700", "800", "900", "1000", "1100", "1200", "1300", "1400", "1500", "1600", "1700", "1800", "1900", "2000", "2100", "2200", "2300", "2400" }));
        ComboBoxDomingoApertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxDomingoAperturaActionPerformed(evt);
            }
        });

        ComboBoxDomingoCierre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "000", "100", "200", "300", "400", "500", "600", "700", "800", "900", "1000", "1100", "1200", "1300", "1400", "1500", "1600", "1700", "1800", "1900", "2000", "2100", "2200", "2300", "2400" }));
        ComboBoxDomingoCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxDomingoCierreActionPerformed(evt);
            }
        });

        CheckBoxLunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxLunesActionPerformed(evt);
            }
        });

        CheckBoxMartes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxMartesActionPerformed(evt);
            }
        });

        CheckBoxMiercoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxMiercolesActionPerformed(evt);
            }
        });

        CheckBoxJueves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxJuevesActionPerformed(evt);
            }
        });

        CheckBoxViernes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxViernesActionPerformed(evt);
            }
        });

        CheckBoxSabado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxSabadoActionPerformed(evt);
            }
        });

        CheckBoxDomingo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxDomingoActionPerformed(evt);
            }
        });

        jLabel12.setText("Para continuar, la hora de cierre debe ser mayor que la hora de apertura,");

        jLabel13.setText("ambas horas deben ser diferentes a 000 y debe haber al menos un dia activo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(CheckBoxLunes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CheckBoxMartes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CheckBoxMiercoles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CheckBoxJueves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CheckBoxViernes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CheckBoxSabado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CheckBoxDomingo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ComboBoxMartesApertura, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ComboBoxLunesApertura, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9)
                                            .addComponent(ComboBoxMiercolesApertura, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ComboBoxJuevesApertura, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ComboBoxViernesApertura, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ComboBoxSabadoApertura, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ComboBoxDomingoApertura, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ComboBoxDomingoCierre, 0, 102, Short.MAX_VALUE)
                                            .addComponent(ComboBoxSabadoCierre, 0, 102, Short.MAX_VALUE)
                                            .addComponent(ComboBoxViernesCierre, 0, 102, Short.MAX_VALUE)
                                            .addComponent(ComboBoxJuevesCierre, 0, 102, Short.MAX_VALUE)
                                            .addComponent(ComboBoxMiercolesCierre, 0, 102, Short.MAX_VALUE)
                                            .addComponent(jLabel10)
                                            .addComponent(ComboBoxLunesCierre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ComboBoxMartesCierre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))))
                        .addGap(0, 94, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9))
                            .addComponent(jLabel11))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxLunesCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxLunesApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CheckBoxLunes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxMartesCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ComboBoxMartesApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(CheckBoxMartes))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckBoxMiercoles, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ComboBoxMiercolesApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CheckBoxJueves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ComboBoxJuevesApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComboBoxMiercolesCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBoxJuevesCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComboBoxViernesCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBoxSabadoCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBoxDomingoCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(ComboBoxViernesApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckBoxViernes, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(ComboBoxSabadoApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckBoxSabado))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckBoxDomingo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(ComboBoxDomingoApertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(34, 34, 34)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVolver)
                    .addComponent(botonContinuar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    
    private boolean verificarHoras(){
        boolean establecidas = true; // si alguna hora de apertura o cierre son iguales a 000 se bloquea el boton de continuar
        // por lo que no se puede guardar 
        int[] horasApertura = { // creamos un array para acceder a los valores de apertura 
            Integer.parseInt(ComboBoxLunesApertura.getSelectedItem().toString()), // es un trainweck un poco confuso pero es necesario pasarlo a string para que selected item lo agarre
            Integer.parseInt(ComboBoxMartesApertura.getSelectedItem().toString()), // y despues se pasa a un integer para guardarlo 
            Integer.parseInt(ComboBoxMiercolesApertura.getSelectedItem().toString()), // creo que puede haber una mejor manera la verdad 
            Integer.parseInt(ComboBoxJuevesApertura.getSelectedItem().toString()), 
            Integer.parseInt(ComboBoxViernesApertura.getSelectedItem().toString()),
            Integer.parseInt(ComboBoxSabadoApertura.getSelectedItem().toString()),
            Integer.parseInt(ComboBoxDomingoApertura.getSelectedItem().toString()),
            
        };
        int [] horasCierre = {
            Integer.parseInt(ComboBoxLunesCierre.getSelectedItem().toString()),
            Integer.parseInt(ComboBoxMartesCierre.getSelectedItem().toString()),
            Integer.parseInt(ComboBoxMiercolesCierre.getSelectedItem().toString()),
            Integer.parseInt(ComboBoxJuevesCierre.getSelectedItem().toString()),
            Integer.parseInt(ComboBoxViernesCierre.getSelectedItem().toString()),
            Integer.parseInt(ComboBoxSabadoCierre.getSelectedItem().toString()),
            Integer.parseInt(ComboBoxDomingoCierre.getSelectedItem().toString()),
            
            
        };        
        
        //establecidas nos permite bloquear el boton de continuar hasta que se cumplan las condiciones
        for (int i = 0; i < horasApertura.length; i++){ 
            if(!listaCheckBox.get(i).isSelected()){ // verificamos que el dia este activado para tomarlo en cuenta en los errores
                continue; // si no esta selecionado se pasa al siguiente ya que sino no esta selecionado no se toma en cuenta para los errores
            }
            
            if (horasApertura[i] == 000 && horasCierre[i] == 000){ // 1 condicion, las horas de apertura y cierre no pueden ser ambas 000
                establecidas = false;
                break;
            }
            if(horasApertura[i] >= horasCierre[i]){ //2 condicion, las horas de cierre deben ser mayores que las de apertura
                establecidas = false;
                break;
            }
        }
        
        return establecidas;
        }
    
        
    private void habilitarContinuar(){
        boolean hayUnDiaActivo = false;
        
        for (JCheckBox checkBox : listaCheckBox){
            if (checkBox.isSelected()){
                hayUnDiaActivo = true;
                break; // con que haya un dia activo ya se puede continuar o sea ya se habilita el boton de crear citas 
                // porque ya hay un horaripara asignar las citas
            }
        }
        if (hayUnDiaActivo){
            botonContinuar.setEnabled(verificarHoras()); // con los dias activos se implementan las condiciones establecidas dentro del metodo verificarhoras
        }
        else{
            botonContinuar.setEnabled(false);
        }
    }
    
    private void actualizarDatos(){
        Barbero barbero = new Barbero();
        
        String lunesAperturaString = ComboBoxLunesApertura.getSelectedItem().toString();
        String lunesCierreString = ComboBoxLunesCierre.getSelectedItem().toString();
        int lunesApertura = Integer.parseInt(lunesAperturaString);
        int lunesCierre = Integer.parseInt(lunesCierreString);
        
        barbero.establecerHorario(DayOfWeek.MONDAY, lunesApertura, lunesCierre);
        barbero.establecerHorario(DayOfWeek.TUESDAY, Integer.parseInt(ComboBoxMartesApertura.getSelectedItem().toString()), Integer.parseInt(ComboBoxMartesCierre.getSelectedItem().toString()));
        barbero.establecerHorario(DayOfWeek.WEDNESDAY, Integer.parseInt(ComboBoxMiercolesApertura.getSelectedItem().toString()), Integer.parseInt(ComboBoxMiercolesCierre.getSelectedItem().toString()));
        barbero.establecerHorario(DayOfWeek.THURSDAY, Integer.parseInt(ComboBoxJuevesApertura.getSelectedItem().toString()), Integer.parseInt(ComboBoxJuevesCierre.getSelectedItem().toString()));
        barbero.establecerHorario(DayOfWeek.FRIDAY, Integer.parseInt(ComboBoxViernesApertura.getSelectedItem().toString()), Integer.parseInt(ComboBoxViernesCierre.getSelectedItem().toString()));
        barbero.establecerHorario(DayOfWeek.SATURDAY, Integer.parseInt(ComboBoxSabadoApertura.getSelectedItem().toString()), Integer.parseInt(ComboBoxSabadoCierre.getSelectedItem().toString()));
        barbero.establecerHorario(DayOfWeek.SUNDAY, Integer.parseInt(ComboBoxDomingoApertura.getSelectedItem().toString()), Integer.parseInt(ComboBoxDomingoCierre.getSelectedItem().toString()));
        
        //System.out.println(horario.horarioSemanal); 
        // aqui cada vez que se da continuar se ejecuta actualizar datos y se imprime en la terminal para ver si se guardan bien 
    }
    
  
    
    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // boton de volver
        this.setVisible(false);
        barberoMenu.setVisible(true);
    }                                           

    private void botonContinuarActionPerformed(java.awt.event.ActionEvent evt) {                                               
        //boton continuar
        actualizarDatos(); // al darle continuar los datos seleccionados se guardan
        
        barberoMenu.habilitarBotonCita(); //al crear el horario, ya se pueden crear citas
        this.setVisible(false);
        barberoMenu.setVisible(true); // volvemos al menu principal
    }                                              
    // ASIGNAR LOS VALORES PARA CADA DIA DE LA SEMANA DESPUES DE ESCOGERLOS
    private void ComboBoxLunesAperturaActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        //apertura lunes
        habilitarContinuar();
    }                                                     

    private void ComboBoxLunesCierreActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        //cierre lunes
        habilitarContinuar();
    }                                                   

    private void ComboBoxMartesAperturaActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        //apertura martes
        habilitarContinuar();
    }                                                      

    private void ComboBoxMartesCierreActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        //cierre martes
        habilitarContinuar();
    }                                                    

    private void ComboBoxMiercolesAperturaActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        //apertura miercoles
        habilitarContinuar();
    }                                                         

    private void ComboBoxMiercolesCierreActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        //cierre miercoles
        habilitarContinuar();
    }                                                       

    private void ComboBoxJuevesAperturaActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        //apertura jueves
        habilitarContinuar();
    }                                                      

    private void ComboBoxJuevesCierreActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        //cierre jueves
        habilitarContinuar();
    }                                                    

    private void ComboBoxViernesAperturaActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        //apertura viernes
        habilitarContinuar();
    }                                                       

    private void ComboBoxViernesCierreActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        //cierre viernes
        habilitarContinuar();
    }                                                     

    private void ComboBoxSabadoAperturaActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        //apertura sabado
        habilitarContinuar();
    }                                                      

    private void ComboBoxSabadoCierreActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        //cierre sabado
        habilitarContinuar();
    }                                                    

    private void ComboBoxDomingoAperturaActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        //apertura domingo
        habilitarContinuar();
    }                                                       

    private void jComboBox15ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        //no se como borrar este, sobra
    }                                           

    private void ComboBoxDomingoCierreActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        //cierre domingo
        habilitarContinuar();
    }                                                     

    private void CheckBoxLunesActionPerformed(java.awt.event.ActionEvent evt) {                                              
        //checkbox lunes
        if (CheckBoxLunes.isSelected()){
            ComboBoxLunesApertura.setEnabled(true);
            ComboBoxLunesCierre.setEnabled(true);
            }
        else{
            ComboBoxLunesApertura.setEnabled(false);
            ComboBoxLunesCierre.setEnabled(false);
        }
        habilitarContinuar();
    }                                             

    private void CheckBoxMartesActionPerformed(java.awt.event.ActionEvent evt) {                                               
        //checkbox martes
        if (CheckBoxMartes.isSelected()){
            ComboBoxMartesApertura.setEnabled(true);
            ComboBoxMartesCierre.setEnabled(true);
            }
        else{
            ComboBoxMartesApertura.setEnabled(false);
            ComboBoxMartesCierre.setEnabled(false);
        }
        habilitarContinuar();          
    }                                              

    private void CheckBoxMiercolesActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        //checkbox miercoles
        if (CheckBoxMiercoles.isSelected()){
            ComboBoxMiercolesApertura.setEnabled(true);
            ComboBoxMiercolesCierre.setEnabled(true);
            }
        else{
            ComboBoxMiercolesApertura.setEnabled(false);
            ComboBoxMiercolesCierre.setEnabled(false);
        }
        habilitarContinuar();       
    }                                                 

    private void CheckBoxJuevesActionPerformed(java.awt.event.ActionEvent evt) {                                               
        //checkbox jueves
         if (CheckBoxJueves.isSelected()){
            ComboBoxJuevesApertura.setEnabled(true);
            ComboBoxJuevesCierre.setEnabled(true);
            }
        else{
            ComboBoxJuevesApertura.setEnabled(false);
            ComboBoxJuevesCierre.setEnabled(false);
        }
        habilitarContinuar();   
    }                                              

    private void CheckBoxViernesActionPerformed(java.awt.event.ActionEvent evt) {                                                
        //checkbox viernes
        if (CheckBoxViernes.isSelected()){
            ComboBoxViernesApertura.setEnabled(true);
            ComboBoxViernesCierre.setEnabled(true);
            }
        else{
            ComboBoxViernesApertura.setEnabled(false);
            ComboBoxViernesCierre.setEnabled(false);
        }
        habilitarContinuar();   
    }                                               

    private void CheckBoxDomingoActionPerformed(java.awt.event.ActionEvent evt) {                                                
        //checkbox domingo
        if (CheckBoxDomingo.isSelected()){
            ComboBoxDomingoApertura.setEnabled(true);
            ComboBoxDomingoCierre.setEnabled(true);
            }
        else{
            ComboBoxDomingoApertura.setEnabled(false);
            ComboBoxDomingoCierre.setEnabled(false);
        }
        habilitarContinuar();   
    }                                               

    private void CheckBoxSabadoActionPerformed(java.awt.event.ActionEvent evt) {                                               
        //checkbox sabado
        if (CheckBoxSabado.isSelected()){
            ComboBoxSabadoApertura.setEnabled(true);
            ComboBoxSabadoCierre.setEnabled(true);
            }
        else{
            ComboBoxSabadoApertura.setEnabled(false);
            ComboBoxSabadoCierre.setEnabled(false);
        }
        habilitarContinuar();   
    }                                              

    

    // Variables declaration - do not modify                     
    private javax.swing.JCheckBox CheckBoxDomingo;
    private javax.swing.JCheckBox CheckBoxJueves;
    private javax.swing.JCheckBox CheckBoxLunes;
    private javax.swing.JCheckBox CheckBoxMartes;
    private javax.swing.JCheckBox CheckBoxMiercoles;
    private javax.swing.JCheckBox CheckBoxSabado;
    private javax.swing.JCheckBox CheckBoxViernes;
    private javax.swing.JComboBox<String> ComboBoxDomingoApertura;
    private javax.swing.JComboBox<String> ComboBoxDomingoCierre;
    private javax.swing.JComboBox<String> ComboBoxJuevesApertura;
    private javax.swing.JComboBox<String> ComboBoxJuevesCierre;
    private javax.swing.JComboBox<String> ComboBoxLunesApertura;
    private javax.swing.JComboBox<String> ComboBoxLunesCierre;
    private javax.swing.JComboBox<String> ComboBoxMartesApertura;
    private javax.swing.JComboBox<String> ComboBoxMartesCierre;
    private javax.swing.JComboBox<String> ComboBoxMiercolesApertura;
    private javax.swing.JComboBox<String> ComboBoxMiercolesCierre;
    private javax.swing.JComboBox<String> ComboBoxSabadoApertura;
    private javax.swing.JComboBox<String> ComboBoxSabadoCierre;
    private javax.swing.JComboBox<String> ComboBoxViernesApertura;
    private javax.swing.JComboBox<String> ComboBoxViernesCierre;
    private javax.swing.JButton botonContinuar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JComboBox<String> jComboBox15;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration                   
}
